(()=>{"use strict";
const JSON_URL="data/SMAE-4ed-normalizado-validado-v7.json";
let db=null,foods=[],current=null,subs=[],subLimit=10,compareA=null,compareB=null,eqFood=null,assistantFood=null;
const $=id=>document.getElementById(id);
const labels={energia:"Energía",proteina:"Proteína",lipidos:"Lípidos",hidratos_carbono:"Hidratos de carbono",fibra:"Fibra",peso_neto:"Peso neto",peso_bruto:"Peso bruto",indice_glicemico:"Índice glicémico",carga_glicemica:"Carga glicémica",sodio:"Sodio",potasio:"Potasio",calcio:"Calcio",hierro:"Hierro",hierro_no_hem:"Hierro no hem",selenio:"Selenio",colesterol:"Colesterol",vitamina_a:"Vitamina A",acido_ascorbico:"Ácido ascórbico",acido_folico:"Ácido fólico"};
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const fmt=v=>v==null||Number.isNaN(Number(v))?"ND":Number(v).toLocaleString("es-MX",{maximumFractionDigits:2});
const nval=(f,k)=>f?.nutrimentos?.[k]?.valor??null;
const est=o=>o?.estado==="estimado"||o?.correccion?.tipo==="estimacion_por_coherencia";
function portion(f){let p=f?.porcion||{};let q=p.cantidad!=null?fmt(p.cantidad):(p.cantidad_fuente||"");return [q,p.unidad].filter(Boolean).join(" ")}
function find(q,limit=12){q=norm(q);if(q.length<2)return[];let a=[],b=[];for(const f of foods){let n=f.nombre_busqueda||norm(f.nombre);(n.startsWith(q)?a:b).push(f)}return a.concat(b).filter(f=>(f.nombre_busqueda||norm(f.nombre)).includes(q)).slice(0,limit)}
function bindSuggest(inputId,boxId,onPick){const input=$(inputId),box=$(boxId);input.addEventListener("input",()=>renderSuggest(find(input.value),box,onPick));input.addEventListener("keydown",e=>{if(e.key==="Enter"){let m=find(input.value,1);if(m.length)onPick(m[0])}if(e.key==="Escape")box.hidden=true});}
function renderSuggest(matches,box,onPick){box.innerHTML="";if(!matches.length){box.hidden=true;return}for(const f of matches){let b=document.createElement("button");b.className="suggestion";b.innerHTML=`<span><strong>${esc(f.nombre)}</strong><br><small>${esc(portion(f))}</small></span><small>${esc(f.grupo)}</small>`;b.onclick=()=>{box.hidden=true;onPick(f)};box.appendChild(b)}box.hidden=false}
async function load(){try{let r=await fetch(JSON_URL,{cache:"no-store"});if(!r.ok)throw 0;db=await r.json()}catch(e){db=window.SMAE_DATA}foods=db.alimentos||[];$("dataStatus").textContent=`Datos locales · ${foods.length.toLocaleString("es-MX")} alimentos`;$("dataStatus").classList.add("ready");populateGroups()}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("view-"+b.dataset.view).classList.add("active")});
bindSuggest("foodSearch","suggestions",selectFood);
function selectFood(f){current=f;$("foodSearch").value=f.nombre;$("searchEmpty").hidden=true;$("foodView").hidden=false;$("foodName").textContent=f.nombre;$("foodGroup").textContent=f.grupo;$("foodPortion").textContent="Porción sugerida: "+portion(f);renderEstimate(f);renderNutrients(f);renderSource(f);buildSubs(f)}
function renderEstimate(f){let items=Object.entries(f.nutrimentos||{}).filter(([,o])=>est(o));$("estimatedBadge").hidden=!items.length;$("estimatedNotice").hidden=!items.length;if(!items.length)return;$("estimatedMessage").textContent=db.politica_uso_aplicacion?.mensaje_usuario_sugerido||"Se utiliza una estimación documentada.";$("estimateDetail").innerHTML=items.map(([k,o])=>{let c=o.correccion||{};return `<strong>${esc(labels[k]||k)}</strong><br>Fuente: ${esc(c.valor_original??o.valor_fuente)} ${esc(o.unidad||"")} · Usado: ${esc(c.valor_estimado??o.valor)} ${esc(o.unidad||"")}${c.intervalo_estimado?`<br>Intervalo: ${c.intervalo_estimado.join("–")} ${esc(o.unidad||"")}`:""}${c.metodo?`<br>Método: ${esc(c.metodo.replaceAll("_"," "))}`:""}`}).join("<hr>")}
$("estimateToggle").onclick=()=>{let d=$("estimateDetail");d.hidden=!d.hidden;$("estimateToggle").textContent=d.hidden?"Ver detalle":"Ocultar detalle"};
function renderNutrients(f){let grid=$("nutrientGrid");grid.innerHTML="";let pr=["energia","proteina","lipidos","hidratos_carbono","fibra","peso_neto","peso_bruto","indice_glicemico","carga_glicemica"];let ks=pr.concat(Object.keys(f.nutrimentos||{}).filter(k=>!pr.includes(k)));for(const k of ks){let o=f.nutrimentos?.[k];if(!o||o.valor==null)continue;let d=document.createElement("div");d.className="nutrient"+(est(o)?" est":"");d.innerHTML=`<div class="lab">${esc(labels[k]||k)}${est(o)?" · estimado":""}</div><div class="val">${fmt(o.valor)}${o.unidad?" "+esc(o.unidad):""}</div>`;grid.appendChild(d)}}
function renderSource(f){let w=f.validacion_semantica?.advertencias||[];$("sourceInfo").innerHTML=`<dt>Documento</dt><dd>${esc(f.fuente?.documento||"SMAE")}</dd><dt>Página</dt><dd>${esc(f.fuente?.pagina_pdf??"ND")}</dd><dt>Estado</dt><dd>${esc(f.validacion_semantica?.estado||"sin advertencias")}</dd><dt>Advertencias</dt><dd>${w.length?esc(w.map(x=>x.codigo).join(", ")):"Ninguna"}</dd>`}
function buildSubs(f){subs=foods.filter(x=>x.id!==f.id&&x.grupo_codigo===f.grupo_codigo).sort((a,b)=>{let t=nval(f,"energia"),ea=nval(a,"energia"),eb=nval(b,"energia");return t!=null&&ea!=null&&eb!=null?Math.abs(ea-t)-Math.abs(eb-t):a.nombre.localeCompare(b.nombre,"es")});subLimit=10;$("subCount").textContent=subs.length;$("subIntro").textContent=`Opciones del mismo grupo/subgrupo: ${f.grupo}.`;renderSubs()}
function renderSubs(){let c=$("substitutes");c.innerHTML="";for(const f of subs.slice(0,subLimit)){let b=document.createElement("button");b.className="sub";b.innerHTML=`<strong>${esc(f.nombre)}</strong><small>${esc(portion(f))}</small><span class="kcal">${nval(f,"energia")==null?"ND":fmt(nval(f,"energia"))+" kcal"}${est(f.nutrimentos?.energia)?" *":""}</span>`;b.onclick=()=>selectFood(f);c.appendChild(b)}$("showMore").hidden=subLimit>=subs.length;$("showMore").textContent=`Ver más (${Math.max(0,subs.length-subLimit)})`}
$("showMore").onclick=()=>{subLimit+=10;renderSubs()};

function populateGroups(){let map=new Map;for(const f of foods)if(!map.has(f.grupo_codigo))map.set(f.grupo_codigo,f.grupo);let s=$("groupSelect");[...map.entries()].sort((a,b)=>a[1].localeCompare(b[1],"es")).forEach(([code,name])=>{let o=document.createElement("option");o.value=code;o.textContent=name;s.appendChild(o)})}
function renderGroup(){let code=$("groupSelect").value,q=norm($("groupFilter").value);let list=foods.filter(f=>!code||f.grupo_codigo===code).filter(f=>!q||norm(f.nombre).includes(q));$("groupSummary").hidden=!code;$("groupSummary").textContent=code?`${list.length.toLocaleString("es-MX")} alimentos en ${$("groupSelect").selectedOptions[0].textContent}.`:"";let c=$("groupFoods");c.innerHTML="";for(const f of list.slice(0,120)){let b=document.createElement("button");b.className="food-mini";b.innerHTML=`<strong>${esc(f.nombre)}</strong><small>${esc(portion(f))} · ${nval(f,"energia")!=null?fmt(nval(f,"energia"))+" kcal":"energía ND"}</small>`;b.onclick=()=>{document.querySelector('[data-view="buscar"]').click();selectFood(f)};c.appendChild(b)}}
$("groupSelect").onchange=renderGroup;$("groupFilter").oninput=renderGroup;

bindSuggest("compareAInput","compareASuggestions",f=>{compareA=f;$("compareAInput").value=f.nombre;renderCompare()});
bindSuggest("compareBInput","compareBSuggestions",f=>{compareB=f;$("compareBInput").value=f.nombre;renderCompare()});
function renderCompare(){if(!compareA||!compareB){$("compareEmpty").hidden=false;$("compareTableWrap").hidden=true;return}$("compareEmpty").hidden=true;$("compareTableWrap").hidden=false;let keys=["energia","proteina","lipidos","hidratos_carbono","fibra","sodio","potasio","calcio","indice_glicemico","carga_glicemica"];let rows=[["Grupo",compareA.grupo,compareB.grupo],["Porción",portion(compareA),portion(compareB)]];for(const k of keys){let a=compareA.nutrimentos?.[k],b=compareB.nutrimentos?.[k];if(!a&&!b)continue;rows.push([labels[k]||k,a?.valor==null?"ND":`${fmt(a.valor)} ${a.unidad||""}${est(a)?" *":""}`,b?.valor==null?"ND":`${fmt(b.valor)} ${b.unidad||""}${est(b)?" *":""}`])}$("compareTable").innerHTML=`<table class="compare-table"><thead><tr><th>Dato</th><th>${esc(compareA.nombre)}</th><th>${esc(compareB.nombre)}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td></tr>`).join("")}</tbody></table><p class="muted">* valor estimado en la base v7.</p>`}

bindSuggest("eqFoodInput","eqSuggestions",f=>{eqFood=f;$("eqFoodInput").value=f.nombre});
$("eqCalculate").onclick=()=>{if(!eqFood){alert("Selecciona un alimento.");return}let n=Number($("eqCount").value);if(!(n>0)){alert("Indica un número de equivalentes mayor que cero.");return}let p=eqFood.porcion||{},qty=p.cantidad;let result=$("eqResult");result.hidden=false;if(qty==null){result.innerHTML=`<h3>${esc(eqFood.nombre)}</h3><p>No fue posible convertir numéricamente la porción fuente. Usa ${esc(p.cantidad_fuente||"la porción indicada")} ${esc(p.unidad||"")} por equivalente.</p>`;return}let total=qty*n;result.innerHTML=`<h3>${esc(eqFood.nombre)}</h3><div class="result-highlight">${fmt(total)} ${esc(p.unidad||"")}</div><p>${fmt(n)} equivalentes × ${fmt(qty)} ${esc(p.unidad||"")} por equivalente.</p><p class="muted">La operación supone que la porción sugerida del registro representa 1 equivalente SMAE.</p>`};

bindSuggest("assistantFoodInput","assistantSuggestions",f=>{assistantFood=f;$("assistantFoodInput").value=f.nombre;addBubble(`Quiero sustituir: ${f.nombre}`,"user");addBubble(`Encontré ${foods.filter(x=>x.id!==f.id&&x.grupo_codigo===f.grupo_codigo).length} opciones del grupo ${f.grupo}. ¿Qué objetivo prefieres?`,"bot");$("assistantGoals").hidden=false});
function addBubble(text,who){let d=document.createElement("div");d.className="bubble "+who;d.textContent=text;$("chat").appendChild(d);$("chat").scrollTop=$("chat").scrollHeight}
document.querySelectorAll("#assistantGoals button").forEach(b=>b.onclick=()=>runAssistant(b.dataset.goal));
function runAssistant(goal){if(!assistantFood)return;let candidates=foods.filter(x=>x.id!==assistantFood.id&&x.grupo_codigo===assistantFood.grupo_codigo);let getter,desc;
if(goal==="similar"){let t=nval(assistantFood,"energia");getter=f=>t==null||nval(f,"energia")==null?999999:Math.abs(nval(f,"energia")-t);desc="más similares en energía"}
if(goal==="menos_energia"){getter=f=>nval(f,"energia")==null?999999:nval(f,"energia");desc="con menor energía"}
if(goal==="mas_fibra"){getter=f=>nval(f,"fibra")==null?999999:-nval(f,"fibra");desc="con mayor fibra"}
if(goal==="menos_sodio"){getter=f=>nval(f,"sodio")==null?999999:nval(f,"sodio");desc="con menor sodio"}
if(goal==="mas_proteina"){getter=f=>nval(f,"proteina")==null?999999:-nval(f,"proteina");desc="con mayor proteína"}
candidates.sort((a,b)=>getter(a)-getter(b));let top=candidates.filter(f=>getter(f)!==999999).slice(0,5);addBubble(`Busco opciones ${desc}.`,"user");if(!top.length){addBubble("No hay datos suficientes para ordenar los sustitutos con ese criterio.","bot");return}let txt=`Sugerencias ${desc}: `+top.map(f=>`${f.nombre} (${portion(f)})`).join("; ")+".";addBubble(txt,"bot")}

document.addEventListener("click",e=>{if(!e.target.closest(".search-wrap"))document.querySelectorAll(".suggestions").forEach(x=>x.hidden=true)});
load();
})();